services:
  ##### NEST API ######
  nest-api:
    container_name: nest-api
    tty: true
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
  
  ##### REACT FRONTEND #####
  react-frontend:
    container_name: react-frontend
    tty: true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${FRONTEND_PORT:-8080}:8080

  ##### MATCHMAKING SERVICE FRONTEND #####
  matchmaking-frontend:
    container_name: matchmaking-frontend
    tty: true
    build:
      context: .
      dockerfile: ./matchmaking/frontend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${MATCHMAKING_FRONTEND_PORT:-7000}:7000

  ##### MATCHMAKING SERVICE BACKEND #####
  matchmaking-backend:
    container_name: matchmaking-backend
    tty: true
    restart: on-failure
    build:
      context: .
      target: prod
      dockerfile: ./matchmaking/backend/Dockerfile
    environment:
      - PGHOST=matchmaking-database
      - PGUSER=${MATCHMAKING_DATABASE_USER:-postgres}
      - PGPASSWORD=${MATCHMAKING_DATABASE_PASSWORD:-postgres}
      - PGDATABASE=matchmaking
      - PGPORT=5432
      - PORT=${MATCHMAKING_BACKEND_PORT:-5005}
    networks:
      - bwu-network
    ports:
      - ${MATCHMAKING_BACKEND_PORT:-5005}:5005
    depends_on:
      matchmaking-database:
        condition: service_healthy

  ##### MATCHMAKING SERVICE DATABASE #####
  matchmaking-database:
    container_name: matchmaking-database
    tty: true
    image: postgres:14.5-alpine
    restart: always
    # You will need to change this if you change MATCHMAKING_DATABASE_USER.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${MATCHMAKING_DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${MATCHMAKING_DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=matchmaking
    networks:
      - bwu-network
    ports:
      - ${MATCHMAKING_DATABASE_PORT:-5009}:5432
    volumes:
      - matchmaking-database-data:/var/lib/postgresql/data
      - ./matchmaking/database/init:/docker-entrypoint-initdb.d

volumes:
  matchmaking-database-data:
    driver: local

networks:
  bwu-network:
    driver: "bridge"
