services:
  ##### NEST API ######
  nest-api:
    container_name: nest-api
    tty: true
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
  
  ##### REACT FRONTEND #####
  react-frontend:
    container_name: react-frontend
    tty: true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${FRONTEND_PORT:-8080}:8080

  ##### MATCHMAKING SERVICE FRONTEND #####
  matchmaking-frontend:
    container_name: matchmaking-frontend
    tty: true
    build:
      context: .
      dockerfile: ./matchmaking/frontend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${MATCHMAKING_FRONTEND_PORT:-7000}:7000

  ##### MATCHMAKING SERVICE BACKEND #####
  matchmaking-backend:
    container_name: matchmaking-backend
    tty: true
    build:
      context: .
      dockerfile: ./matchmaking/backend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${MATCHMAKING_BACKEND_PORT:-5005}:5005

networks:
  bwu-network:
    driver: "bridge"
