services:
  ##### NEST API ######
  nest-api:
    container_name: nest-api
    tty: true
    build:
      #target: prod
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
  
  ##### REACT FRONTEND #####
  react-frontend:
    container_name: react-frontend
    tty: true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - bwu-network
    ports:
      - ${FRONTEND_PORT:-8081}:8080

networks:
  bwu-network:
    driver: "bridge"
