# TEMPLATE for use in root directory.
# - Create a docker-compose.override.yaml with the following config.
### File starts below ###

# For use in development.
# Overrides default docker-compose configurations.

services:
  ##### IMB CAMPUS SERVICE BACKEND #####
  imbc-backend:
    build:
      target: dev
  ##### IMB CAMPUS SERVICE FRONTEND #####
  imbc-frontend:
    build:
      target: dev
    volumes:
      - ./matchmaking/frontend/src:/app/src

