const axios = require("axios");
const qs = require("qs");

const {
  SSO_CLIENT_ID,
  SSO_CLIENT_SECRET,
  OIDC_AUTHORIZATION_URL,
  OIDC_TOKEN_URL,
  OIDC_USER_INFO_URL,
  OIDC_LOGOUT_URL,
  OIDC_GRANT_TYPE,
  OIDC_REDIRECT_URL,
  OIDC_RESPONSE_TYPE,
  OIDC_SCOPE,
  OIDC_LOGOUT_REDIRECT_URL,
} = require("../config");

const btoa = (string) => Buffer.from(string).toString("base64");

/**
 *
 * @author Zach Bourque <Zachary.Bourque@gov.bc.ca>
 * @description Decodes the given base64 encoded string into JSON.
 */
const decodeValue = (base64String) => {
  try {
    return JSON.parse(Buffer.from(base64String, "base64").toString("ascii"));
  } catch {
    return "";
  }
};

/**
 *
 * @author Zach Bourque <Zachary.Bourque@gov.bc.ca>
 * @description Given a JWT access token, decode it and return the JSON result
 */
const decodingJWT = (token) => {
  if (!token) return null;

  const [header, payload] = token.split(".");

  return {
    header: decodeValue(header),
    payload: decodeValue(payload),
  };
};

/**
 *
 * @author Zach Bourque <Zachary.Bourque@gov.bc.ca>
 * @description Creates a URL for the user to be redirected to for login, using our Keycloak integration details.
 */
const getAuthorizationUrl = async (baseURL) => {
  const params = {
    client_id: SSO_CLIENT_ID,
    response_type: OIDC_RESPONSE_TYPE,
    scope: OIDC_SCOPE,
    redirect_uri: baseURL + OIDC_REDIRECT_URL,
  };

  return `${OIDC_AUTHORIZATION_URL}?${qs.stringify(params, { encode: false })}`;
};

/**
 *
 * @author Zach Bourque <Zachary.Bourque@gov.bc.ca>
 * @description Given the authorization code given after the user logs in, fetch an access_token and refresh_token for the given user.
 */
const getAccessToken = async ({ code, baseURL }) => {
  const url = OIDC_TOKEN_URL;
  const params = {
    grant_type: OIDC_GRANT_TYPE,
    client_id: SSO_CLIENT_ID,
    redirect_uri: baseURL + OIDC_REDIRECT_URL,
    code,
  };

  const config = {
    url,
    method: "POST",
    data: qs.stringify(params),
  };
  if (SSO_CLIENT_SECRET) {
    config.headers = {
      Authorization: `Basic ${btoa(`${SSO_CLIENT_ID}:${SSO_CLIENT_SECRET}`)}`,
    };
  }

  const { data } = await axios(config);

  const { id_token, access_token, refresh_token } = data;

  // Decode tokens to get user information
  data.id_token_decoded = decodingJWT(id_token);

  data.access_token_decoded = decodingJWT(access_token);

  data.refresh_token_decoded = decodingJWT(refresh_token);

  return data;
};

/**
 *
 * @author Zach Bourque <Zachary.Bourque@gov.bc.ca>
 * @description Retrieves the userInfo for the user with the specified accessToken
 */
const getUserInfo = async ({ accessToken }) => {
  const { data } = await axios({
    url: OIDC_USER_INFO_URL,
    method: "get",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  return data;
};

/**
 *
 * @author Zach Bourque <Zachary.Bourque@gov.bc.ca>
 * @description Creates a logout URL for the given user, based on our Keycloak integration credentials.
 */
const getLogoutUrl = (baseURL) => {
  const params = {
    client_id: SSO_CLIENT_ID,
    redirect_uri: baseURL + OIDC_LOGOUT_REDIRECT_URL,
  };

  return `${OIDC_LOGOUT_URL}?${qs.stringify(params, { encode: false })}`;
};

/**
 *
 * @author Zach Bourque <Zachary.Bourque@gov.bc.ca>
 * @description Tests the given JWT token and validates that it is both generated by the same issuer, and is not expired.
 */
const isJWTValid = async (jwt) => {
  let headersList = {
    Accept: "*/*",
    "Content-Type": "application/x-www-form-urlencoded",
  };

  let bodyContent = `client_id=${config.SSO_CLIENT_ID}&client_secret=${config.SSO_CLIENT_SECRET}&token=${jwt}`;

  let response = await fetch(config.OIDC_INTROSPECT_URL, {
    method: "POST",
    body: bodyContent,
    headers: headersList,
  });

  let data = await response.json();
  return data.active;
};

module.exports = {
  getAuthorizationUrl,
  getAccessToken,
  getUserInfo,
  getLogoutUrl,
  isJWTValid,
};
