name: Matchmaking - Frontend

on:
  push:
    branches: [ main ]
    paths:
      - "matchmaking/frontend/**"
  workflow_dispatch:
  
jobs:
  MM-Frontend-Build-Tag-Push:
    environment: MM-Frontend-Dev
    runs-on: ubuntu-latest
    steps:
    
      # Checkout BCGov/citz-imb-build-with-us-1 Github Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Openshift Silver Cluster
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: github-actions
          OPENSHIFT_NAMESPACE: ec1236-tools
        with: 
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}
          namespace: ec1236-tools
            
      # Login to BC Gov Docker Image Repository
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_PUBLIC_IMAGE_REPOSITORY_BASE_URL }} -u ${{ secrets.OPENSHIFT4_TOOLS_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}
      
      # Build the MM API Application Image via docker-compose
      - name: Build the Docker image
        run: |
          docker-compose build matchmaking-frontend
      
      # TROUBLESHOOTING - view images present in github action run
      - name: Docker List Images
        run: |
          docker image ls 
      
      # Tag Docker Image built with latest
      - name: Docker Tag Version
        run: |
          docker tag citz-imb-build-with-us-1_matchmaking-frontend image-registry.apps.silver.devops.gov.bc.ca/ec1236-tools/match-making-frontend:latest
      # Push docker image to BC Gov Repository  
      - name: Docker Push Version
        run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/ec1236-tools/match-making-frontend:latest
