apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-template
labels:
  template: ${APPLICATION_NAME}-template
objects:

- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    annotations:
      app.openshift.io/route-disabled: 'false'
      openshift.io/generated-by: OpenShiftWebConsole
    name: ${APPLICATION_NAME}
    generation: 2
    namespace: ${LICENSE_PLATE}-${ENVIRONMENT}
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: match-making
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: ImageStreamTag
            namespace: ${LICENSE_PLATE}-tools
            name: '${IMAGESTREAM}:latest'
          lastTriggeredImage: >-
            image-registry.openshift-image-registry.svc:5000/ec1236-tools/match-making-api@sha256:c3d57523a0277faacef24e3703b31f42dbfb3fbde88b3c27036886f7abaad78c
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        containers:
          - name: ${APPLICATION_NAME}
            image: >-
              image-registry.openshift-image-registry.svc:5000/ec1236-tools/match-making-api@sha256:c3d57523a0277faacef24e3703b31f42dbfb3fbde88b3c27036886f7abaad78c
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: SSO_SESSION_SECRET
                valueFrom:
                  secretKeyRef:
                    name: matchmaking-sso
                    key: MATCHMAKING_SSO_SESSION_SECRET
              - name: SSO_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: matchmaking-sso
                    key: MATCHMAKING_SSO_CLIENT_SECRET
              - name: SSO_AUTH_SERVER_URL
                value: 'https://dev.loginproxy.gov.bc.ca/auth'
              - name: SSO_REALM
                value: standard
              - name: SSO_CLIENT_ID
                value: im-boarding-4554
              - name: PORT
                value: '7000'
              - name: FRONTEND_REF
                value: ' match-making-frontend'
              - name: ENVIRONMENT
                value: dev
              - name: PGPORT
                valueFrom:
                  secretKeyRef:
                    name: postgres-config
                    key: PGPORT
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: postgres-config
                    key: PGUSER
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-config
                    key: PGPASSWORD
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: postgres-config
                    key: PGHOST
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    name: postgres-config
                    key: PGDATABASE
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler

parameters:
  - description: Application Name
    displayName: AppName
    name: APPLICATION_NAME
    required: true
    value: imbc-api
  - description: Environment
    displayName: Environment
    name: ENVIRONMENT
    required: true
    value: dev
  - description: License Plate
    displayName: License Plate
    name: LICENSE_PLATE
    required: true
    value: ec1236
  - description: Imagestream
    displayName: Imagestream
    name: IMAGESTREAM
    required: true
    value: 'imbc-api'
